### ISSUE TITLE
Makefile?

### ISSUE THREAD

**Issue by DerrickMartinez** [uswitch/sqs-autoscaler-controller#3]
Is there a Makefile available for this project? I would love to try it but can’t get it to compile. Also the image url is down.

Thanks

**Comment by pingles** [comment]
Hi @DerrickMartinez- could you include the compilation errors you get please? Building should be as simple as cloning and running:

```
$ go build -o ./bin/controller main.go
```

The image we build on our Drone instance is hosted within a private repository. I'll create another issue to change it so we push to our public org on Quay.io like the other projects.

**Comment by DerrickMartinez** [comment]
For some reason it doesn't appear to be trying to use the vendor directory

`$ go version
go version go1.9 darwin/amd64`

`$ go build -o ./bin/controller main.go
main.go:10:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/github.com/Sirupsen/logrus (from $GOROOT)
	/Users/dmartinez02/go/src/github.com/Sirupsen/logrus (from $GOPATH)
main.go:11:2: cannot find package "github.com/pubnub/go-metrics-statsd" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/github.com/pubnub/go-metrics-statsd (from $GOROOT)
	/Users/dmartinez02/go/src/github.com/pubnub/go-metrics-statsd (from $GOPATH)
main.go:12:2: cannot find package "github.com/rcrowley/go-metrics" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/github.com/rcrowley/go-metrics (from $GOROOT)
	/Users/dmartinez02/go/src/github.com/rcrowley/go-metrics (from $GOPATH)
main.go:19:2: cannot find package "github.com/uswitch/sqs-autoscaler-controller/pkg/crd" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/github.com/uswitch/sqs-autoscaler-controller/pkg/crd (from $GOROOT)
	/Users/dmartinez02/go/src/github.com/uswitch/sqs-autoscaler-controller/pkg/crd (from $GOPATH)
main.go:20:2: cannot find package "github.com/uswitch/sqs-autoscaler-controller/pkg/scaler" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/github.com/uswitch/sqs-autoscaler-controller/pkg/scaler (from $GOROOT)
	/Users/dmartinez02/go/src/github.com/uswitch/sqs-autoscaler-controller/pkg/scaler (from $GOPATH)
main.go:13:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
	/Users/dmartinez02/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)
main.go:14:2: cannot find package "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset (from $GOROOT)
	/Users/dmartinez02/go/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset (from $GOPATH)
main.go:15:2: cannot find package "k8s.io/client-go/kubernetes" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/k8s.io/client-go/kubernetes (from $GOROOT)
	/Users/dmartinez02/go/src/k8s.io/client-go/kubernetes (from $GOPATH)
main.go:16:2: cannot find package "k8s.io/client-go/rest" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/k8s.io/client-go/rest (from $GOROOT)
	/Users/dmartinez02/go/src/k8s.io/client-go/rest (from $GOPATH)
main.go:17:2: cannot find package "k8s.io/client-go/tools/clientcmd" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/k8s.io/client-go/tools/clientcmd (from $GOROOT)
	/Users/dmartinez02/go/src/k8s.io/client-go/tools/clientcmd (from $GOPATH)`

Thanks for posting to quay btw. I'll give it a try right now

**Comment by pingles** [comment]
@DerrickMartinez most likely you didn't clone into your `$GOPATH` properly- the go tool would then be unable to find all the vendor'ed deps as above. It'd need to be cloned into `$GOPATH/src/github.com/uswitch/sqs-autoscaler-controller`.

I'm going to close this issue for now.

**Comment by DerrickMartinez** [comment]
yeah I got it to compile just fine, thanks
